server:
  port: 9958

spring:
  profiles:
    active: dev
  main:
    #禁用循环依赖
    allow-circular-references: true
#  datasource:
#    druid:
#      driver-class-name: ${}
#      url:
#      username:
#      password:

mybatis:
  #mapper配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ybb.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      ybb:
        mapper: debug
        service: info
        controller: info


ybb:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: smart_ybb
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
