server:
  port: 9958
#  servlet:
#    context-path: /sc

spring:
  profiles:
    active: dev
  main:
    #禁用循环依赖
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${smart.datasource.driver-class-name}
    url: jdbc:mysql://${smart.datasource.host}:${smart.datasource.port}/${smart.datasource.database}?characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=GMT%2B8
    username: ${smart.datasource.username}
    password: ${smart.datasource.password}


mybatis:
  #mapper配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ybb.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      ybb:
        mapper: debug
        service: info
        controller: info


ybb:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    jwt_secret_key: smart_ybb
    # 设置jwt过期时间
    jwt-ttl: 7200000
    # 设置前端传递过来的令牌名称
    jwt-token-name: token
